FROM python:3.12-slim

RUN apt-get update
RUN apt-get -y install gcc

# Основной путь приложения
ENV SRC_DIR=/opt
ENV TESTS_DIR=$SRC_DIR/tests
ENV LOGS_DIR=$SRC_DIR/logs

# Путь до приложения fastapi
ENV APP_DIR=$SRC_DIR/app
ENV APP_USER=order-user

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    GUNICORN_PROCESSES=4 \
    GUNICORN_CONNECTIONS=8 \
    GUNICORN_LOGLEVEL='error'

# Создание no-root пользователя
RUN mkdir $LOGS_DIR

# Установка зависимостей
WORKDIR $APP_DIR

ENV DJANGO_SETTINGS_MODULE 'config.settings'
ENV PATH="/$SRC_DIR/.local/bin:${PATH}"

RUN pip install --upgrade pip && \
    pip install --no-cache-dir poetry

COPY pyproject.toml pyproject.toml
#COPY src/requrements.txt requrements.txt

RUN poetry install --with test

# Копирования кода приложения
COPY ./ $APP_DIR

COPY /entrypoint.sh /usr/local/bin/entrypoint.sh
