[tool.poetry]
name = "content api"
version = "0.1.0"
description = "api of lms's content"
authors = ["Nozir Tukhramurodov <nozir9407@gmail.com>"]
license = "MIT" 

[tool.poetry.dependencies]
python = "^3.12"
gunicorn = "^22.0.0"
redis = "^5.0.8"
django = "^5.0.7"
django-split-settings = "^1.3.2"
python-dotenv = "^1.0.1"
psycopg2-binary = "^2.9"
uvicorn = "^0.30.4"
pillow = "^10.4.0"
django-phonenumber-field = {version = "^8.0.0", extras = ["phonenumbers"]}
django-nested-admin = "^4.1.1"
django-tinymce = "^4.1.0"
django-ckeditor = "^6.7.1"
<<<<<<< HEAD
django-jazzmin = "^3.0.0"
=======
>>>>>>> main

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
flake8-bugbear = "^24.1.17"
flake8-isort = "^6.1.1"
flake8-bandit = "^4.1.1"
flake8-pytest-style = "^1.7.2"
flake8-pytest = "^1.4"
flake8-print = "^5.0.0"
flake8-commas = "^2.1.0"
flake8-broken-line = "^1.0.0"
isort = "^5.13.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
faker = "^22.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

